### ISSUE TITLE
[Doc] Installing bicho 

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/bicho#15]
#Hi Duncan,

i like bicho, but i'm not a ruby packager expert :)

I was thinking, maybe we could add a small section, to guide how to install bicho. (even if ruby gems installation is a common stuff, i had my problems too .. :)

Could be user friendly then :)

#### Installing bicho
```
git clone BICHO.git; cd bicho
bundler.ruby2.1  install 
gem install bicho
```
Don't know if it's the correct order :)

**Comment by MalloZup** [comment]
wow it works, i think is the right order ! :) 

If you are ok with this, i will make a PR soon :)

**Comment by dmacvicar** [comment]
why don't you install directly from rubygems?

`gem install bicho`

I have also built a package for the latest released gem:

https://build.opensuse.org/package/show/devel:languages:ruby:extensions/rubygem-bicho

**Comment by MalloZup** [comment]
yop, thx :)
